language: python
python:
  - 3.4
  - 3.5
  - 3.6
  - 3.7

script: true

branches:
  only:
    - master
    - /^v\d+\.\d+(\.\d+)?(-\S*)?$/ # version tags

notifications:
  email:
    on_success: never
